swagger: '2.0'
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      description: Get all users
      responses:
        200:
          description: List of users
    post:
      description: Create a new user
      parameters:
        - name: name
          in: body
          required: true
          type: string
        - name: email
          in: body
          required: true
          type: string
      responses:
        200:
          description: User created successfully
